{{- if .Values.deploy.ingress.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.global.serviceName }}-ca-cert'
type: Opaque
data:
  '{{ (.Files.Glob "Certificates/*").AsSecrets | indent 2 }}'
{{- end }}