apiVersion: v1
kind: Service
metadata:
  name: '{{ include "app.name" . }}-{{ .Values.global.serviceName }}'
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.deploy.serviceType }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
  ports:
    {{- tpl (toYaml .Values.deploy.ports) . | nindent 4 }}