apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-app-of-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: argocd-plugin
  source:
    path: GitOps/ArgoApps/Plugin
    repoURL: 'https://github.com/tal-hason/argocd-plugin-generator.git'
    targetRevision: pull-request-plugin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true