---
# Source: app/templates/header-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: 'argocd-app-set-plugin-token'
  labels:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: argo-plugin
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
type: Opaque
data:
  token: 'T0Yxc0dNazJaTmlTQmo='
---
# Source: app/templates/secret-ca-cert.yaml
apiVersion: v1
kind: Secret
metadata:
  name: 'plugin-ca-cert'
  labels:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: argo-plugin
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
type: Opaque
data:
    _.apps-crc.testing: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEV3pDQ0FrT2dBd0lCQWdJSUY1WU9PVVcyTldNd0RRWUpLb1pJaHZjTkFRRUxCUUF3SmpFa01DSUdBMVVFDQpBd3diYVc1bmNtVnpjeTF2Y0dWeVlYUnZja0F4TmpnME56VTFOell3TUI0WERUSXpNRFV5TWpFeE5ESTBNbG9YDQpEVEkxTURVeU1URXhOREkwTTFvd0hURWJNQmtHQTFVRUF3d1NLaTVoY0hCekxXTnlZeTUwWlhOMGFXNW5NSUlCDQpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcit5WWVwY3VLWkpCZDNESStYQVNNd2V0DQpSSm1nRjhndHBJR3RzUExjN2k2NGlybUZhNkd4QVJicThoN3RwTzY4aXFqOU5sUG9EN2lSYVo3a0pBS05tMmVnDQorK0pCZmRVZHhHL2l5SWZUWTRaVkdiYnd3VHB5MW1HRzNsNzdFYzZMTFd1OC9PU2ZPcDdFUitUU1lNa1ZMblY4DQpBSDZ6MjlSSWhOWjRWQUpaU013K2R4d0pVZE4yNGxsVlBsaDJ5Y1R2ZExYSFVibWtkalhCOWtJVzl0ZUJaeHRsDQpsb2hiYlJxMCtjNnJmZ3kvNXBERjJLNWsvQnhRTTd2R3JLT1hJSEI5SjMzNmZVbi9OQXg1alBieW1wNWxHelNpDQpqR1Z0a1V5VSsrTnk0MVhRSU5qVTJvVzZNQzd2Q0JGVllZbnFCU0c3eUJzOE9SalJYbWYwQnVVMHVSY3Fzd0lEDQpBUUFCbzRHVk1JR1NNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFNDQpCZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJUeEtVMXU5TFRaOEVMbFUzeXdidkttS3N1UE9qQWZCZ05WDQpIU01FR0RBV2dCUlZaZGllOHQzWjRremlxUEN0K0hVSkZRNlhTakFkQmdOVkhSRUVGakFVZ2hJcUxtRndjSE10DQpZM0pqTG5SbGMzUnBibWN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdpNXlVekhJNjZwcEFWQ091dGl6c1huDQptRXVDTk9VZTU3UXdsa0dabDdDeXA0M0ZCL3ZGdHlpb2FwWXl1bzNHZElXNUtYZThxU2pPTEtvQzJhK2NwUVlGDQp1dDd3USt1Z3RNY2o5K0xvRndhTG45b0szRXBaUEhhcXBQUnhjQ3NSSGpkRFZ6RnJ1MTN5WStDWWlrbVdaVExLDQorakpkczNZU0ZCelpTNUh3Y2FIRzY0bjFCK1RpMHVGRjlMbE5CamJ5bWJ2dGppNjBySFJhRFk5TlNXZ282bnpSDQpOR1d4UC90R1NJeWVRUjVZampnYWZ2M21zUG5tbzRmVDUvK2lsL1J1TWtSWGxrU2ZJQTZnV1pGdWwwQVpxS0RHDQpTaWlqRU1IeTBQN0ljUDJJUTE5MmtNVUtKR0FIbmxJdjZJTHZaNTBDck1NWllublJLblhnSDRGYkVaYjBKTXc9DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tDQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0NCk1JSURERENDQWZTZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0cGJtZHkNClpYTnpMVzl3WlhKaGRHOXlRREUyT0RRM05UVTNOakF3SGhjTk1qTXdOVEl5TVRFME1qTTVXaGNOTWpVd05USXgNCk1URTBNalF3V2pBbU1TUXdJZ1lEVlFRRERCdHBibWR5WlhOekxXOXdaWEpoZEc5eVFERTJPRFEzTlRVM05qQXcNCmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURPOHNtOEQ2Z1Q0YjlKQ2lzUHZLT3gNCkhXQS9pcGJBQ0xZcFZXbFE5L2p4Vi9wOTlaSE1rVlV3SStMd1ZoWmV2em1ubkNXR1pISTBCc1djVEVpWVRscFANClRPSzMvbUEyaSswSzhTUDM3TFZnZW5KamplRXlVQWpNMGU1YkdOTUN4M25tU1pDMDdXRExwandXdkw2UVFrMlMNCjBMYXNhbWQzenJQK2FycVpMaGZLS1BiU255aktSOWpCUjdDTjZWR1ZFVTB5bzhqakN2Y2VnaElpK1l2YVY0Zm0NCmo4S3orZUVyWEh4dW9Za1NJNlVrVUF4UDk2c3pwTEEzUGhMZGY5Y2dJTUtDQzk0TGsyOEdCOXduOHFsclZBTC8NClZ2bHF4QWNxMHYxTVRaRFp2SjAxWW9ZVC9Jb3lzUUxxN0x4b3ZEM0RZdjF0NEhCZi9CT0hpcS9Pd21JVnByMlQNCkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUVBd0lDcERBU0JnTlZIUk1CQWY4RUNEQUdBUUgvQWdFQU1CMEcNCkExVWREZ1FXQkJSVlpkaWU4dDNaNGt6aXFQQ3QrSFVKRlE2WFNqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUENClkwY3hwQktaY1Q4eWNSVFVIZXBlRHBhSVNsUGpORTdlZVROOFJsUUZyRTZEYWYxUmI5VVNqMVQ0RTBKdlorbG0NCm42OVZWdVd1MkVvOTlLMzh4R1d0NmR0S3UxQWFEOU5rVVJGSXBDZWc4RVI2ZUk2SWRPdGJ3cmRRSEpCd3RQN2kNClBwcXN2VVFlRHd1THVBRnMwUXFJZmtCS0NUdmEwTkNDUWU1UXY3TDh1bnorNlpacjVBU0RYd2ZCYi9MVXg2RU8NCjFXWmczNS9FYWg2UFlrajh5MXc4dGUzakxtUFh6VFVzVW8rM0JLVXZlQ0ZtTmVPZHhoY3VpTitWMFZyZ1ZaaTQNCm9xMHV1eUJhejJoTURLWTMwWSt6djR3STFlSGFBUkNKU3Njbyt5Mm1PT0FYaDFXaFp4L2diSEFuNHRCbnZpN1INCnZUQldMRktkbEYrRGVjSHJXL3kxM1E9PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K
---
# Source: app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: applicationset-file
  labels:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: argo-plugin
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
data:
    app.yaml: |-
    GenerateApplication:
      - hello: world
      - hello: again
---
# Source: app/templates/plugin-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugin-config
  labels:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: argo-plugin
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
data:
  token: "$argocd-app-set-plugin-token:token" # Alternatively $<some_K8S_secret>:plugin.myplugin.token
  baseUrl: 'http://argo-plugin-plugin.svc'
---
# Source: app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: 'argo-plugin-plugin'
  labels:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: argo-plugin
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
---
# Source: app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'argo-plugin-plugin'
  labels:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: argo-plugin
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-plugin
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argo-plugin
        app.kubernetes.io/instance: test
        app.kubernetes.io/part-of: argo-plugin
        app.kubernetes.io/managed-by: argocd
        app.openshift.io/runtime: nodejs
      annotations:
        checksum/config: 69ff6ccdaa1e744df0d03cb132be257a3cf5980f1e45a52abe0e2b0bd6616b5c
    spec:
      containers:
        - name: plugin
          image: quay.io/thason/argocd-appset-plugin:8fbd529
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: http
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: http
          env:
            - name: PORT
              value: 8080
          volumeMounts:
            - mountPath: /var/run/argo/token
              name: token
            - mountPath: /tmp/config/
              name: applications
      volumes:
        - Secret:
            key: token
            name: argocd-app-set-plugin-token
          name: token
        - configMap:
            name: applicationset-file
          name: applications
---
# Source: app/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 'argo-plugin-plugin'
  labels:
    app.kubernetes.io/name: argo-plugin
    app.kubernetes.io/instance: test
    app.kubernetes.io/part-of: argo-plugin
    app.kubernetes.io/managed-by: argocd
    app.openshift.io/runtime: nodejs
  annotations:
    route.openshift.io/termination: edge 
    route.openshift.io/destination-ca-certificate-secret: plugin-ca-cert
spec:
  rules:
  - host: plugin-argo-plugin-openshift-gitops.apps-crc.testing
    http:
      paths:
      - backend:
          service:
            name: 'argo-plugin-plugin'
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - {}
