apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.global.serviceName }}-applicationset-file'
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "ApplcaitionFiles/*").AsConfig | nindent 2 }}
