apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.global.serviceName }}-plugin-config'
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  token: "${{ .Values.global.serviceName }}-argocd-app-set-plugin-token:token"
  baseUrl: 'http://{{ include "app.name" . }}-{{ .Values.global.serviceName }}:8080'
