{{- if .Values.deploy.ingress.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Values.global.serviceName }}-ca-cert'
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
{{ (.Files.Glob "Certificates/*").AsSecrets | nindent 2 }}
{{- end }}