GenerateApplication:
  - name: batman
    project: gotham-demo
    image: quay.io/gotham/batman
    tag: 4a7050d
  - name: joker
    project: gotham-demo
    image: quay.io/gotham/joker
    tag: 8280f51
  - name: robin
    project: gotham-demo
    image: quay.io/gotham/robin
    tag: a678098