apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: delete-app-from-branch
spec:
  params:
    - default: 'xxx'
      name: branch_name
      type: string
    - default: 'xxx'
      name: repository_name
      type: string
    - default: 'xxx'
      name: project_name
      type: string
    - default: 'xxx'
      name: gitops-branch
      type: string
  steps:
    - args:
        - '-c'
        - >
          set -ex

          git switch $(params.gitops-branch)

          git config --global --add safe.directory $(workspaces.output.path)

          git pull

          # Run commands for closed pull request

          echo "PR is closed. Running script for closed PR."

          export BRANCH=$(params.branch_name)

          export BRANCH=$(echo ${BRANCH} | awk '{print tolower($0)}')

          export REPO=$(params.repository_name)

          export REPO=$(echo ${REPO} | awk '{print tolower($0)}')

          export PROJECT=$(params.project_name)

          export PROJECT=$(echo ${PROJECT} | awk '{print tolower($0)}')

          pwd

          cd $(workspaces.output.path)/GitOps/Argo-Plugin/ApplicationFiles

          ls -l

          rm $REPO-$BRANCH.yaml

          echo "Delete PR Branch from the Plugin Repo"

      command:
        - /bin/bash
      image: 'quay.io/argocicd/update-deploy:pipeline'
      name: update-chart-app-ver
      workingDir: /workspace/output/
      resources: {}
  workspaces:
    - description: The git repo will be cloned onto the volume backing this Workspace.
      name: output

