apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-app-from-branch
spec:
  params:
    - default: 'xxx'
      name: branch_name
      type: string
    - default: 'xxx'
      name: tag
      type: string
    - default: 'xxx'
      name: repository_name
      type: string
    - default: 'xxx'
      name: project_name
      type: string
    - default: 'xxx'
      name: gitops-branch
      type: string
  steps:
    - args:
        - '-c'
        - >
          set -ex

          git config --global --add safe.directory $(workspaces.output.path)

          git switch $(params.gitops-branch)

          git pull

          # Run commands for opened pull request

          echo "PR is open. Running script for open PR."

          export BRANCH=$(params.branch_name)

          export BRANCH=$(echo ${BRANCH} | awk '{print tolower($0)}')

          export REPO=$(params.repository_name)

          export REPO=$(echo ${REPO} | awk '{print tolower($0)}')

          export PROJECT=$(params.project_name)

          export PROJECT=$(echo ${PROJECT} | awk '{print tolower($0)}')

          export DATETIME=$(date +"%Y-%m-%d_%H:%M:%S")

          pwd

          cd $(workspaces.output.path)/GitOps/Argo-Plugin/ApplicationFiles

          echo "GenerateApplication:" > $REPO-$BRANCH.yaml

          echo "  branch: ${BRANCH}" >> $REPO-$BRANCH.yaml

          echo "  tag: $(params.tag)" >> $REPO-$BRANCH.yaml

          echo "  repoName: ${REPO}" >> $REPO-$BRANCH.yaml

          echo "  projectName: ${PROJECT}" >> $REPO-$BRANCH.yaml

          echo "  dateTime: ${DATETIME}" >> $REPO-$BRANCH.yaml

          cat $REPO-$BRANCH.yaml

          echo "Updating the Plugin Repo"

      command:
        - /bin/bash
      image: 'quay.io/argocicd/update-deploy:pipeline'
      name: update-chart-app-ver
      workingDir: /workspace/output/
      resources: {}
  workspaces:
    - description: The git repo will be cloned onto the volume backing this Workspace.
      name: output

