apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-app-from-branch
spec:
  params:
    - default: '1234'
      name: service-name
      type: string
    - default: 'gh-token'
      name: git-secret-name
      type: string
  steps:
    - args:
        - '-c'
        - >
          set -ex

          pwd

          ls -l

          cd 

      command:
        - /bin/bash
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: $(params.git-secret-name)
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: $(params.git-secret-name)
      image: 'quay.io/argocicd/update-deploy:pipeline'
      name: update-chart-app-ver
      workingDir: /workspace/output/
      resources: {}
  workspaces:
    - description: The git repo will be cloned onto the volume backing this Workspace.
      name: output
