apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pull-request-template
spec:
  params:
    - description: Pull Request state
      name: pr_state
    - description: The Url of the source repo
      name: repo_url
    - description: the branch name source from the PR
      name: from_branch
    - description: the sha of the head of the branch
      name: commit_sha
    - description: The name of the repository
      name: repo_name
    - description: The full name of the repository
      name: repo_full_name
    - description: The name of the orgenization
      name: repo_org_name
    - description: the 7 first charecters of the commit head
      name: truncated_sha
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: TaskRun
      metadata:
        generateName: testing-run-
      spec:
        taskSpec:
          steps:
            - image: 'quay.io/argocicd/update-deploy:pipeline'
              script: |
                #! /bin/bash
                echo "test test"
                echo "pr_state is : $(tt.params.pr_state)" 
                echo "repo_url is : $(tt.params.repo_url)"
                echo "from_branch is : $(tt.params.from_branch)" 
                echo "commit_sha is : $(tt.params.commit_sha)"
                echo "repo_name is : $(tt.params.repo_name)"
                echo "repo_full_name is : $(tt.params.repo_full_name)"
                echo "repo_org_name is : $(tt.params.repo_org_name)"
                echo "truncated_sha is : $(tt.params.truncated_sha)"    