apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pull-request-template
spec:
  params:
    - description: Pull Request state
      name: pr_state
    - description: The Url of the source repo
      name: repo_url
    - description: the branch name source from the PR
      name: from_branch
    - description: the sha of the head of the branch
      name: commit_sha
    - description: The name of the repository
      name: repo_name
    - description: The full name of the repository
      name: repo_full_name
    - description: The name of the orgenization
      name: repo_org_name
    - description: the 7 first charecters of the commit head
      name: truncated_sha
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pull-reqeust-run-
      spec:
        params:
          - name: PLUGIN_REPO
            value: 'https://github.com/tal-hason/argocd-plugin-generator.git'
          - name: PLUGIN_BRANCH
            value: pull-request
        pipelineRef:
          name: pull-request
        serviceAccountName: pipeline
        timeouts:
          pipeline: 1h0m0s
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              metadata:
                creationTimestamp: null
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 150Mi
                storageClassName: crc-csi-hostpath-provisioner
                volumeMode: Filesystem
              status: {} 